# configuration values for the project

GEE_PROJECT_NAME = 'fast-ability-467118-m8'	# Google Earth Engine project name

GEE_SCALE = 30 # in meters

# Path to the GeoJSON file defining the region of interest
# Currently, this can be provided with command line arguments.
BOUNDARY_GEOJSON_PATH = './tifs/delhi.geojson'

# The following tifs will be downloaded by scripts.
DEMFILE_PATH = './tifs/dem.tif'
SOIL_PATH = './tifs/soil.tif'
LULC_PATH = './tifs/lulc.tif'

# Folder where rainfall data from GEE is downloaded to
RAINFALL_FOLDER = './tifs/rainfall3/'
RUNOFFS_FOLDER = './tifs/runoffs3/'

# The output file.
TIMESERIES_VECTOR = './tifs/timeseries.geojson'

ARG_START_DATE = '2017-07-01'
ARG_END_DATE = '2025-06-18'
